# Generated by Django 4.2.4 on 2023-08-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_for_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
